name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAIL_PASSWORD_SCRIPTS: ${{ secrets.MAIL_PASSWORD_SCRIPTS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to server
      run: |
        php my_script.php
